api:
  dashboard: true

entryPoints:
  accesspoint:
    address: ":9600"
  accesspointdashboard:
    address: ":9601"
  accesspointmetrics:
    address: ":9602"
  accesspointdb:
    address: ":9603"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
    filename: middlewares.yml

metrics:
  prometheus:
    entryPoint: accesspointmetrics
    addEntryPointsLabels: true
    addServicesLabels: true
